import Head from "next/head";
import { GetStaticProps } from "next";
import api from "./api";
import { Flex, Img, Stack } from "@chakra-ui/react";

interface IMovie {
  adult: boolean;
  backdrop_path: string;
  id: number;
  title: string;
  original_language: string;
  original_title: string;
  overview: string;
  poster_path: string;
  media_type: string;
  genre_ids: Array<number>;
  popularity: number;
  release_date: string;
  video: boolean;
  vote_average: number;
  vote_count: number;
}

interface IHomeProps {
  data: {
    results: IMovie[];
  };
}

export default function Home({ data }: IHomeProps) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/" />
      </Head>
      <main>
        {data.results.map((movie) => (
          <Flex>
            <Stack>
              <Img
                src={`https://image.tmdb.org/t/p/w500/${movie.poster_path}`}
                alt={movie.title}
              />
              <p> {movie.poster_path}</p>
            </Stack>
          </Flex>
        ))}
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await api.get("trending/movie/day");
  return {
    props: {
      data,
    },
    revalidate: 2,
  };
};
